### PR TITLE
feat: 🎸 add skip internal contest

### PR DESCRIPTION
**Pull request by yoofa**

### CODE REVIEW

**Comment by yoofa** [comment]
LeetCode.cn may host internal contests for testing purposes, which we can disregard.
Let us introduce a skip_internal_contest option to filter these out.
Test OK on https://lccal-worker.youfa.site/ical?region=CN&skip_internal_contest

**Comment by Gowee** [comment]
> LeetCode.cn may host internal contests for testing purposes, which we can disregard.

Are these internal contests actually accessible by normal users? If not, I think it would be better to filter them out by default.

**Comment by yoofa** [comment]
I have observed that the contest at the URL https://leetcode.cn/contest/internal-dynamic-contest03-2 has remained unchanged for several months, suggesting it serves as a testing mechanism.

Previously, I just wanted to add an option to filter internal contests without changing the default logic, but now I set it to true by default.


> > LeetCode.cn may host internal contests for testing purposes, which we can disregard.
> 
> Are these internal contests actually accessible by normal users? If not, I think it would be better to filter them out by default.

**Comment by Gowee** [comment]
We follow the camelCase naming convention. Could you please change the variable name from `skip_internal_contest` to `skipInternalContest` across all files? It is fine to use it as a param name in URL, though.

**Comment by yoofa** [comment]
> We follow the camelCase naming convention. Could you please change the variable name from `skip_internal_contest` to `skipInternalContest` across all files? It is fine to use it as a param name in URL, though.

Done

**Comment by Gowee** [comment]
Thank you!

**Pull request merged**
